<%@ page contentType = "text/xml; charset=UTF-8" %>

<%
	//ContentType
	response.setContentType("text/xml; charset=UTF-8");
	response.setHeader("Cache-Control", "max-age=0, must-revalidate");

	System.out.println("getWorkFlowDefById.jsp");
	System.out.println("id="+request.getParameter("id"));
%>

<workFlow
		id="101"
>
		<statusTypeList>
				<statusType
						id="201"
						seq="1"
						kind="301"
						auto="false"
				>
						<nameList>
								<name
										lang="JA"
										value="ステータスタイプ１"
								/>
								<name
										lang="EN"
										value="Status Type 1"
								/>
						</nameList>
						<asEntryList>
								<userList>
										<user
												id="401"
												name="ユーザ１"
										/>
										<user
												id="402"
												name="ユーザ２"
										/>
								</userList>
								<groupList>
										<group
												id="501"
												name="グループ１"
										/>
										<group
												id="502"
												name="グループ２"
										/>
								</groupList>
								<roleList>
										<role
												id="601"
												name="ロール１"
										/>
										<role
												id="602"
												name="ロール２"
										/>
								</roleList>
								<compGroupList>
										<compGroup
												id="701"
												name="複合グループ１"
										/>
										<compGroup
												id="702"
												name="複合グループ２"
										/>
								</compGroupList>
								<userDefGroupList>
										<userDefGroup
												id="-501"
												name="ユーザ定義グループ１"
										/>
										<userDefGroup
												id="-502"
												name="ユーザ定義グループ２"
										/>
								</userDefGroupList>
								<sysFuncList>
										<sysFuncGroup
												id="-601"
												name="システム処理１"
										/>
										<sysFuncGroup
												id="-602"
												name="システム処理２"
										/>
								</sysFuncList>
						</asEntryList>
				</statusType>
				<statusType
						id="202"
						seq="2"
						kind="302"
						auto="false"
				>
						<nameList>
								<name
										lang="JA"
										value="ステータスタイプ２"
								/>
								<name
										lang="EN"
										value="Status Type 2"
								/>
						</nameList>
						<asEntryList>
								<userList>
										<user
												id="403"
												name="ユーザ３"
										/>
										<user
												id="404"
												name="ユーザ4"
										/>
								</userList>
								<groupList>
										<group
												id="503"
												name="グループ3"
										/>
										<group
												id="504"
												name="グループ3"
										/>
								</groupList>
								<roleList>
										<role
												id="603"
												name="ロール３"
										/>
										<role
												id="603"
												name="ロール４"
										/>
								</roleList>
								<compGroupList>
										<compGroup
												id="703"
												name="\複合グループ3"
										/>
										<compGroup
												id="704"
												name="複合グループ4"
										/>
								</compGroupList>
								<userDefGroupList>
										<userDefGroup
												id="-503"
												name="ユーザ定義グループ3"
										/>
										<userDefGroup
												id="-504"
												name="ユーザ定義グループ4"
										/>
								</userDefGroupList>
								<sysFuncList>
										<sysFuncGroup
												id="-603"
												name="システム処理3"
										/>
										<sysFuncGroup
												id="-604"
												name="システム処理4"
										/>
								</sysFuncList>
						</asEntryList>
				</statusType>
		</statusTypeList>
		<eventTypeList>
				<eventType
						id="801"
						seq="1"
						fromStatusTypeSeq="1"
						fromStatusTypeName="ステータスタイプ１"
						toStatusTypeSeq="2"
						toStatusTypeName="ステータスタイプ２"
						baseEventTypeId="-201"
						baseEventTypeName="ベースイベントタイプ１"
						guardConditionId="-101"
						guardConditionName="ガード条件１"
				>
						<nameList>
								<name
										lang="JA"
										value="イベントタイプ１"
								/>
								<name
										lang="EN"
										value="Event Type 1"
								/>
						</nameList>
						<mailList>
								<mail
										id="-401"
										name="メール種別１"
										method="immediate"
										sendType="split"
								/>
								<mail
										id="-402"
										name="メール種別２"
										method="accumulate"
										sendType="bundle"
								/>
						</mailList>
				</eventType>
		</eventTypeList>
</workFlow>
